#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FootballUpdateWidget.Resource", IsApplication=true)]

namespace FootballUpdateWidget
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontPath = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int border_top = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int borderLayout_White = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int borderlayout_white2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int borderRight = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int branchOpenLayout2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cardLayout = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cardStyle2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int distanceFromUser2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int distanceLayout2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int epl = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int epl2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_epl2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_update = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_update_black_24dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_update_black_36dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int materialCard = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int materiaRow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Mockup2_ButtonRedBorder = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Mockup2_ButtonRedBorder2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Mockup2_LayoutBorder = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Mockup2_SignupButtonRed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Mockup2_TextFieldLowerBorder = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int nav_color_select = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int refresh = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int roundbutton_green = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int roundbutton_layout = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int roundbutton_layout2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int roundbutton_layout3 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int roundbutton_layout4 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int roundbutton_layout5 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int roundbutton_layout6 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int roundbutton_layoutBlue = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roundCard_layout = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundCardDark_Layout = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int scheduleTemplate = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int spinnerStyle = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int textfield_round = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int textfield_roundhardedge = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int textFields2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int textFields3 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int textfields4 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int textfields5 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int uneditableTextLayout = 2130837548;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int calligraphy_tag_id = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int eplNeedRefresh = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int eplTeamsGrid = 2131099654;
			
			// aapt resource value: 0x7f06002a
			public const int exp2 = 2131099690;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f06001b
			public const int leagueIcon = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int leagueName = 2131099676;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout2 = 2131099650;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout3 = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout4 = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout5 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout6 = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout7 = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout8 = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout9 = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int standingUpdate = 2131099653;
			
			// aapt resource value: 0x7f060020
			public const int team1 = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int team1Points = 2131099685;
			
			// aapt resource value: 0x7f060021
			public const int team2 = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int team2Points = 2131099686;
			
			// aapt resource value: 0x7f060022
			public const int team3 = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int team3Points = 2131099687;
			
			// aapt resource value: 0x7f060023
			public const int team4 = 2131099683;
			
			// aapt resource value: 0x7f060028
			public const int team4Points = 2131099688;
			
			// aapt resource value: 0x7f060024
			public const int team5 = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int team5Points = 2131099689;
			
			// aapt resource value: 0x7f06001d
			public const int teamUpdateButton = 2131099677;
			
			// aapt resource value: 0x7f060008
			public const int textView1 = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060018
			public const int textView3 = 2131099672;
			
			// aapt resource value: 0x7f06001f
			public const int textView4 = 2131099679;
			
			// aapt resource value: 0x7f06001a
			public const int updateTime = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int widget_team1 = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int widget_team1points = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int widget_team2 = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int widget_team2points = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int widget_team3 = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int widget_team3points = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int widget_team4 = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int widget_team4points = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int widget_team5 = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int widget_team5points = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int eplLineupWidget = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_update2 = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int appwidgetprovider = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
